{"name": "test_add1[4-13-9]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 17 == 9\n +  where 17 = add(4, 13)", "trace": "self = <test_case.test_3.TestAbc object at 0x04B0B478>, a = 4, b = 13, c = 9\n\n    def test_add1(self,a,b,c):  # => 作为用例参数，接收装饰器传入的数据\n>       assert add(a, b) == c\nE       assert 17 == 9\nE        +  where 17 = add(4, 13)\n\ntest_case\\test_3.py:9: AssertionError"}, "parameters": [{"name": "a", "value": "4"}, {"name": "b", "value": "13"}, {"name": "c", "value": "9"}], "start": 1605858878646, "stop": 1605858878646, "uuid": "bf7b5d73-387f-468a-bb4a-d2fbe07b4f9b", "historyId": "3365129b481dd54d95eaa70f462f92a3", "testCaseId": "6be17bcdc0f680365db331b191b27036", "fullName": "test_case.test_3.TestAbc#test_add1", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_3"}, {"name": "subSuite", "value": "TestAbc"}, {"name": "host", "value": "DESKTOP-EQA5M9D"}, {"name": "thread", "value": "14276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_3"}]}